version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-build phase started
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build phase started!!
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Post-build phase entered
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: dist 